---
- hosts: localhost
  tasks:
          - name: deploying war into tomcat server
            copy:
                    src: /home/vagrant/ansible/workspace/project_pipeline/project_pipeline_package/target/addressbook-2.0.war
                    dest: /usr/local/latest/webapps
                    remote_src: false
            become: yes
                     
