---
- hosts: localhost
  tasks:
          - name: deploying war into tomcat server
            copy:
                    src: /var/lib/jenkins/workspace/project_pipeline/project_pipeline_package/target/addressbook-2.0.war
                    dest: /usr/local/apache-tomcat-8.5.66/webapps
                    remote_src: yes
            become: yes
                     
